version: '3.9'
services:
  postgres:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/

  postgres_admin:
    depends_on:
      - postgres
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@user.user
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 80:80

volumes:
  database-data: